### ISSUE TITLE
Setup Production API Deployment

### ISSUE THREAD

**Issue by ChrispyPeaches** [ChrispyPeaches/FocusFriends#74]
## Problem
As a developer, I can deploy the Focus API to production

## Definition of Done
- Flow/process for deploying updates is documented
- prod API can be used by users downloading the app
- All members of the team have access to managing the API

## Subtasks
- [ ] Find a service to deploy onto (needs to support docker compose. I was looking at Google Cloud) 
- [ ] Create other subtasks

**Comment by iggy808** [comment]
Still need to document this process, but PROD server is up on GCP

**Comment by ChrispyPeaches** [comment]
Completed
